### ISSUE TITLE
YA DVA GODA ZDAL TAKOI MOD!!!!11!

### ISSUE THREAD

**Issue by Voltoran** [sononio/labyrinth#1]
Здраствуйте. Я хотел бы чтобы вы сделали mod,  суть такова... Пользователь может играть лесными slaves in labyrinth. Ну и на лабаирит еще минотав набигает, и чтоюбы юлоки не рушились а лабирит сложный и вверх нельзя и подземлю не доступно ничего вообщем очень прошк слуайте плз

**Comment by sononio** [comment]
Ваш отзыв очень важен для нас. Конечно, все описанные функции находятся в разработке. Ожидайте релиза в ближайшее время.
